version: '3.8'

services:
  web:
    build: .
    container_name: web
    ports:
      - "8080:80"
    links:
      - db
    volumes:
      - ./php:/var/www/html
    restart: always
    networks:
      - totonetwork
  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: app_db
    ports:
      - "6033:3306"
    volumes:
      - ./data:/var/lib/mysql
    restart: always
    networks:
      - totonetwork
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8081:80"
    networks:
      - totonetwork
volumes:
  dbdata:
networks:
  totonetwork: